site_name: Armar by Taylored Technology
theme: material
markdown_extensions:
    - pymdownx.tasklist
    - admonition
    - codehilite(guess_lang=false)
    - toc(permalink=true)
extra_css:
    - css/custom.css
extra:
  palette:
    primary: 'blue grey'
    accent: 'amber'
  logo: 'images/ttlogo.jpg'
repo_name: 'tayloredtechnology/armar'
repo_url: 'https://github.com/tayloredtechnology/armar'
site_favicon: 'images/favicon.ico'
